"use client";

import React, { use } from "react";
import Link from "next/link";
import { ArrowLeft, Clock, Calendar, Share2, Sparkles } from "lucide-react";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import BackgroundEffects from "@/components/ui/BackgroundEffects";

interface BlogPostProps {
  params: Promise<{
    slug: string;
  }>;
}

const postsData: Record<string, {
  title: string;
  category: string;
  date: string;
  readTime: string;
  content: string[];
}> = {
  "transforming-learning-through-generative-ai": {
    title: "Transforming Learning Through Generative AI",
    category: "AI & Education",
    date: "June 20, 2026",
    readTime: "5 min read",
    content: [
      "In the modern corporate ecosystem, continuous learning is no longer a luxury—it is an absolute necessity. However, traditional training methods often fall short when adapting to individualized student styles or rapid updates in operational environments. This is where customized Generative AI steps in.",
      "By tailoring LLMs to retrieve real-time context from internal enterprise wikis, companies are creating custom AI tutors that walk users through complex processes step-by-step. The results are striking: onboarding cycle times are reduced by up to 50%, and employees retain information far more effectively.",
      "As we move forward, the intersection of specialized knowledge bases and responsive chat interfaces will refine how companies think about workforce scaling and continuous development."
    ]
  },
  "building-secure-enterprise-ai-integrations": {
    title: "Building Secure Enterprise AI Integrations",
    category: "Security",
    date: "June 15, 2026",
    readTime: "8 min read",
    content: [
      "When bringing artificial intelligence into an enterprise context, data security stands as the primary challenge. Standard public API integrations run the risk of exposing sensitive proprietary data to third-party model retraining cycles.",
      "To build a truly secure integration, architects must deploy private VPC gateways, enforce end-to-end data encryption, and implement robust semantic filters that evaluate data inputs and outputs before they leave local infrastructure.",
      "Enforcing strict role-based access control (RBAC) ensures that individuals only access data they are authorized to see, protecting both client confidentiality and corporate data sovereignty."
    ]
  },
  "the-future-of-automated-knowledge-discovery": {
    title: "The Future of Automated Knowledge Discovery",
    category: "Productivity",
    date: "June 08, 2026",
    readTime: "6 min read",
    content: [
      "The sheer volume of text data generated by modern teams makes finding precise answers to everyday questions incredibly difficult. Studies show that knowledge workers spend up to 20% of their time simply searching for information.",
      "Optimized Retrieval-Augmented Generation (RAG) models resolve this issue by converting unstructured content from disparate channels into semantic vector databases. This enables instant question-answering with verifiable citations back to internal sources.",
      "The future belongs to context-aware search tools that not only locate files but synthesize clear, actionable decisions across multiple tools simultaneously."
    ]
  }
};

export default function BlogPostDetail({ params }: BlogPostProps) {
  const { slug } = use(params);

  const post = postsData[slug] || {
    title: "Article Not Found",
    category: "System",
    date: "N/A",
    readTime: "0 min read",
    content: ["The requested article could not be found. Please return to the blog list."]
  };

  return (
    <main className="relative min-h-screen bg-black text-white selection:bg-purple-500/30 selection:text-purple-200 overflow-hidden">
      <BackgroundEffects />
      <Navbar />

      <article 
        style={{ paddingTop: "190px" }}
        className="relative z-10 w-full max-w-3xl mx-auto px-6 md:px-12 pb-28"
      >
        {/* Back Link */}
        <Link
          href="/blog"
          className="inline-flex items-center gap-2 text-xs font-semibold tracking-wider text-zinc-400 hover:text-white transition-colors mb-12 group cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4 transform group-hover:-translate-x-1 transition-transform" />
          Back to Blog
        </Link>

        {/* Post Metadata Header */}
        <header className="flex flex-col gap-6 mb-12 border-b border-white/5 pb-10">
          <div className="flex items-center gap-3 text-xs font-semibold uppercase tracking-widest text-blue-400">
            <Sparkles className="w-4 h-4" />
            {post.category}
          </div>
          
          <h1 className="text-3xl md:text-5xl font-extrabold tracking-tight leading-tight text-white">
            {post.title}
          </h1>

          <div className="flex items-center gap-6 text-xs text-zinc-500 font-semibold">
            <div className="flex items-center gap-1.5">
              <Calendar className="w-4 h-4" />
              <span>{post.date}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <Clock className="w-4 h-4" />
              <span>{post.readTime}</span>
            </div>
          </div>
        </header>

        {/* Content Body */}
        <section className="flex flex-col gap-6 text-zinc-300 text-base md:text-lg leading-relaxed font-normal mb-16">
          {post.content.map((paragraph, index) => (
            <p key={index}>{paragraph}</p>
          ))}
        </section>

        {/* Footer share */}
        <footer className="flex items-center justify-between border-t border-white/5 pt-8">
          <span className="text-xs text-zinc-500 font-semibold">Written by EdFoal AI Team</span>
          <button className="flex items-center gap-2 text-xs font-semibold tracking-wide text-zinc-400 hover:text-white transition-colors">
            <Share2 className="w-4 h-4" />
            Share Post
          </button>
        </footer>
      </article>

      <Footer />
    </main>
  );
}
